<div class="middleBar" style="width: 60%">
	<table class="table table-striped" >
		<tr><th colspan="5"><?php echo $this->translate('Core Folders')?></th></tr>
		<?php if (empty($this->aCoreFolders)) :?>
		<?php echo '<tr>
						<td colspan="5">
							<div class="alert alert-warning" role="alert"><i>'.$this->translate('No core folders set ').'</i></div>
						</td>
					</tr>'?>
		<?php else:?>
			<?php
				foreach($this->aCoreFolders as $aFolder)
				{
					$aSummary = Docs::getSummary($aFolder['id'], 0);
					echo '<tr>
							<td style="text-align: center; width: 80px;">';
								echo "<button type='button' class='btn btn-default btn-xs'
								onclick=\"location.href='{$this->baseUrl()}/docs/core-folders/folder_id/{$aFolder['id']}'\">
									<span class='glyphicon glyphicon-edit'></span>
								   ".$this->translate('Edit')."
								</button>";
							echo '</td>
							<td style="text-align: left;">'.$aFolder['title'].'</td>
							<td style="text-align: center;">'.$aSummary['folders'].' '.$this->translate('Folders').'</td>
							<td style="text-align: center; width: 50px;">'.$aSummary['files'].' '.$this->translate('Files').'</td>
							<td style="text-align: center; width: 50px;">';
								echo "<a onclick=\"return confirmDelete('{$this->baseUrl()}/docs/core-folders/', $aFolder[id])\">{$this->sDeleteBtn}</a>";
							echo '</td>
						</tr>';
				}
			?>
		<?php endif?>
	</table>
</div>
<!--side bar -->
<div class="rightBar" style="width: 30%">
	<?php echo $this->sForm?>
</div>