<?php
echo Zend_Version::VERSION;
echo '
<div class="middleBar" >';

echo <<<HTML
	<div class="row">
		<div class="col-md-4 jjdev-margin-top-5">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">{$this->translate('Follow Our Development Team')}</h3>
				</div>
				<div class="panel-body">
					<p class="text text-primary">{$this->translate('Our development team can be joined and share views on social networks')}</p>
					<p><a class="btn btn-primary btn-xs pull-left">{$this->translate('Find Out')} &raquo;</a></p>
				</div>
			</div>
		</div>
		<div class="col-md-4 jjdev-margin-top-5">
			<div class="panel panel-success">
				<div class="panel-heading">
					<h3 class="panel-title">{$this->translate('Discover Modules')}</h3>
				</div>
				<div class="panel-body">
					<p class="text text-success">{$this->translate('Our development team can be joined and share views on social networks')}</p>
					<p><a class="btn btn-success btn-xs pull-left">{$this->translate('Find Out')} &raquo;</a></p>
				</div>
			</div>
		</div>

		<div class="col-md-4 jjdev-margin-top-5">
			<div class="panel panel-warning">
				<div class="panel-heading">
					<h3 class="panel-title">{$this->translate('Help and Support')}</h3>
				</div>
				<div class="panel-body">
					<p class="text text-warning">{$this->translate('Our development team can be joined and share views on social networks')}</p>
					<p><a class="btn btn-warning btn-xs pull-left">{$this->translate('Find Out')} &raquo;</a></p>
				</div>
			</div>
		</div>
		<div class="col-md-4 jjdev-margin-top-5">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">{$this->translate('Follow Our Development Team')}</h3>
				</div>
				<div class="panel-body">
					<p class="text text-primary">{$this->translate('Our development team can be joined and share views on social networks')}</p>
					<p><a class="btn btn-primary btn-xs pull-left">{$this->translate('Find Out')} &raquo;</a></p>
				</div>
			</div>
		</div>
		<div class="col-md-4 jjdev-margin-top-5">
			<div class="panel panel-success">
				<div class="panel-heading">
					<h3 class="panel-title">{$this->translate('Discover Modules')}</h3>
				</div>
				<div class="panel-body">
					<p class="text text-success">{$this->translate('Our development team can be joined and share views on social networks')}</p>
					<p><a class="btn btn-success btn-xs pull-left">{$this->translate('Find Out')} &raquo;</a></p>
				</div>
			</div>
		</div>

		<div class="col-md-4 jjdev-margin-top-5">
			<div class="panel panel-warning">
				<div class="panel-heading">
					<h3 class="panel-title">{$this->translate('Help and Support')}</h3>
				</div>
				<div class="panel-body">
					<p class="text text-warning">{$this->translate('Our development team can be joined and share views on social networks')}</p>
					<p><a class="btn btn-warning btn-xs pull-left">{$this->translate('Find Out')} &raquo;</a></p>
				</div>
			</div>
		</div>
		<div class="col-md-4 jjdev-margin-top-5">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">{$this->translate('Follow Our Development Team')}</h3>
				</div>
				<div class="panel-body">
					<p class="text text-primary">{$this->translate('Our development team can be joined and share views on social networks')}</p>
					<p><a class="btn btn-primary btn-xs pull-left">{$this->translate('Find Out')} &raquo;</a></p>
				</div>
			</div>
		</div>
		<div class="col-md-4 jjdev-margin-top-5">
			<div class="panel panel-success">
				<div class="panel-heading">
					<h3 class="panel-title">{$this->translate('Discover Modules')}</h3>
				</div>
				<div class="panel-body">
					<p class="text text-success">{$this->translate('Our development team can be joined and share views on social networks')}</p>
					<p><a class="btn btn-success btn-xs pull-left">{$this->translate('Find Out')} &raquo;</a></p>
				</div>
			</div>
		</div>
		<div class="col-md-4 jjdev-margin-top-5">
			<div class="panel panel-warning">
				<div class="panel-heading">
					<h3 class="panel-title">{$this->translate('Help and Support')}</h3>
				</div>
				<div class="panel-body">
					<p class="text text-warning">{$this->translate('Our development team can be joined and share views on social networks')}</p>
					<p><a class="btn btn-warning btn-xs pull-left">{$this->translate('Find Out')} &raquo;</a></p>
				</div>
			</div>
		</div>
			<br/>
		<div class="col-md-4 jjdev-margin-top-5">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">{$this->translate('Follow Our Development Team')}</h3>
				</div>
				<div class="panel-body">
					<p class="text text-primary">{$this->translate('Our development team can be joined and share views on social networks')}</p>
					<p><a class="btn btn-primary btn-xs pull-left">{$this->translate('Find Out')} &raquo;</a></p>
				</div>
			</div>
		</div>
		<div class="col-md-4 jjdev-margin-top-5">
			<div class="panel panel-success">
				<div class="panel-heading">
					<h3 class="panel-title">{$this->translate('Discover Modules')}</h3>
				</div>
				<div class="panel-body">
					<p class="text text-success">{$this->translate('Our development team can be joined and share views on social networks')}</p>
					<p><a class="btn btn-success btn-xs pull-left">{$this->translate('Find Out')} &raquo;</a></p>
				</div>
			</div>
		</div>
		<div class="col-md-4 jjdev-margin-top-5">
			<div class="panel panel-warning">
				<div class="panel-heading">
					<h3 class="panel-title">{$this->translate('Help and Support')}</h3>
				</div>
				<div class="panel-body">
					<p class="text text-warning">{$this->translate('Our development team can be joined and share views on social networks')}</p>
					<p><a class="btn btn-warning btn-xs pull-left">{$this->translate('Find Out')} &raquo;</a></p>
				</div>
			</div>
		</div>
	</div>
HTML;
echo <<<HTML
</div><!-- end of the middle bar div-->
HTML;

?>
<!--Right Bar-->
<div class="rightBar">
</div>


