<div class="middleBar jjdev-full-width">
	<div class="row">
		<div class="col-md-3 jjdev-margin-top-5">
			<div class="panel panel-success">
				<div class="panel-heading">
					<h3 class="panel-title">
						<?php echo $this->translate('Cell Groups')?>
					</h3>
				</div>
				<div class="panel-body">
					<p class="text text-success">
						Cell Groups
					</p>
					<div>
						<div class="pull-left"><?php echo $this->translate('View More')?></div>
						<div class="pull-right"><span class="glyphicon glyphicon-circle-arrow-right"></span></div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-3 jjdev-margin-top-5">
			<div class="panel panel-success">
				<div class="panel-heading">
					<h3 class="panel-title">
						<?php echo $this->translate('Zones')?>
					</h3>
				</div>
				<div class="panel-body">
					<p class="text text-success">
						Zones
					</p>
					<div>
						<div class="pull-left"><?php echo $this->translate('View More')?></div>
						<div class="pull-right"><span class="glyphicon glyphicon-circle-arrow-right"></span></div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-3 jjdev-margin-top-5">
			<div class="panel panel-success">
				<div class="panel-heading">
					<h3 class="panel-title">
						<?php echo $this->translate('Ministries')?>
					</h3>
				</div>
				<div class="panel-body">
					<p class="text text-success">
						Ministries
					</p>
					<div>
						<div class="pull-left"><?php echo $this->translate('View More')?></div>
						<div class="pull-right"><span class="glyphicon glyphicon-circle-arrow-right"></span></div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-3 jjdev-margin-top-5">
			<div class="panel panel-success">
				<div class="panel-heading">
					<h3 class="panel-title">
						<?php echo $this->translate('Membership')?>
					</h3>
				</div>
				<div class="panel-body">
					<p class="text text-success">
						Members
					</p>
					<div>
						<div class="pull-left"><?php echo $this->translate('View More')?></div>
						<div class="pull-right"><span class="glyphicon glyphicon-circle-arrow-right"></span></div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-3 jjdev-margin-top-5">
			<div class="panel panel-success">
				<div class="panel-heading">
					<h3 class="panel-title">
						<?php echo $this->translate('Cell Groups')?>
					</h3>
				</div>
				<div class="panel-body">
					<p class="text text-success">
						Cell Groups
					</p>
					<div>
						<div class="pull-left"><?php echo $this->translate('View More')?></div>
						<div class="pull-right"><span class="glyphicon glyphicon-circle-arrow-right"></span></div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-3 jjdev-margin-top-5">
			<div class="panel panel-success">
				<div class="panel-heading">
					<h3 class="panel-title">
						<?php echo $this->translate('Zones')?>
					</h3>
				</div>
				<div class="panel-body">
					<p class="text text-success">
						Zones
					</p>
					<div>
						<div class="pull-left"><?php echo $this->translate('View More')?></div>
						<div class="pull-right"><span class="glyphicon glyphicon-circle-arrow-right"></span></div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-3 jjdev-margin-top-5">
			<div class="panel panel-success">
				<div class="panel-heading">
					<h3 class="panel-title">
						<?php echo $this->translate('Ministries')?>
					</h3>
				</div>
				<div class="panel-body">
					<p class="text text-success">
						Ministries
					</p>
					<div>
						<div class="pull-left"><?php echo $this->translate('View More')?></div>
						<div class="pull-right"><span class="glyphicon glyphicon-circle-arrow-right"></span></div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-3 jjdev-margin-top-5">
			<div class="panel panel-success">
				<div class="panel-heading">
					<h3 class="panel-title">
						<?php echo $this->translate('Membership')?>
					</h3>
				</div>
				<div class="panel-body">
					<p class="text text-success">
						Members
					</p>
					<div>
						<div class="pull-left"><?php echo $this->translate('View More')?></div>
						<div class="pull-right"><span class="glyphicon glyphicon-circle-arrow-right"></span></div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-3 jjdev-margin-top-5">
			<div class="panel panel-success">
				<div class="panel-heading">
					<h3 class="panel-title">
						<?php echo $this->translate('Cell Groups')?>
					</h3>
				</div>
				<div class="panel-body">
					<p class="text text-success">
						Cell Groups
					</p>
					<div>
						<div class="pull-left"><?php echo $this->translate('View More')?></div>
						<div class="pull-right"><span class="glyphicon glyphicon-circle-arrow-right"></span></div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-3 jjdev-margin-top-5">
			<div class="panel panel-success">
				<div class="panel-heading">
					<h3 class="panel-title">
						<?php echo $this->translate('Zones')?>
					</h3>
				</div>
				<div class="panel-body">
					<p class="text text-success">
						Zones
					</p>
					<div>
						<div class="pull-left"><?php echo $this->translate('View More')?></div>
						<div class="pull-right"><span class="glyphicon glyphicon-circle-arrow-right"></span></div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-3 jjdev-margin-top-5">
			<div class="panel panel-success">
				<div class="panel-heading">
					<h3 class="panel-title">
						<?php echo $this->translate('Ministries')?>
					</h3>
				</div>
				<div class="panel-body">
					<p class="text text-success">
						Ministries
					</p>
					<div>
						<div class="pull-left"><?php echo $this->translate('View More')?></div>
						<div class="pull-right"><span class="glyphicon glyphicon-circle-arrow-right"></span></div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-3 jjdev-margin-top-5">
			<div class="panel panel-success">
				<div class="panel-heading">
					<h3 class="panel-title">
						<?php echo $this->translate('Membership')?>
					</h3>
				</div>
				<div class="panel-body">
					<p class="text text-success">
						Members
					</p>
					<div>
						<div class="pull-left"><?php echo $this->translate('View More')?></div>
						<div class="pull-right"><span class="glyphicon glyphicon-circle-arrow-right"></span></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>