<?php
/**
 * Author: jimlink
 * Date: 7/27/2016
 * Time: 9:08 PM
 * Copyright (c) JJDEV
 * @version 1.0 (excellence)
 */

$aMinistry = $this->aMinistry;
$sDateStarted = ($aMinistry['date_started'] > 0) ? date('D d M Y', $aMinistry['date_started']) : 'Not Set';
$sDateCreated = ($aMinistry['date_created'] > 0) ? date('D d M Y', $aMinistry['date_created']) : 'Not Set';
$sGroupLeader = isset($aMinistry['firstname']) ? $aMinistry['firstname'] . ' ' . $aMinistry['surname'] : 'Not Set';
$sActivate = ($aMinistry['is_active'] == 1) ? 'Deactivate' : 'Activate';
$sActivateClass = ($aMinistry['is_active'] == 1) ? 'warning' : 'success';
$sActivateIcon = ($aMinistry['is_active'] == 1) ? 'ban-circle' : 'check';

echo '<div class="row">
	<div class="col-md-6">
		<table class="table table-responsive table-striped">
			<thead>
				<tr><td colspan="2"><div class="jjdev-page-header">'.$this->translate('Ministry Full View').'</div></td></tr>
			</thead>
			<tbody>
				<tr><td class="caption">'.$this->translate('Name').'</td><td>'.$aMinistry['ministry_name'].'</td></tr>
				<tr><td class="caption">'.$this->translate('Short Name').'</td><td>'.$aMinistry['known_as'].'</td></tr>
				<tr><td class="caption">'.$this->translate('Ministry Leader').'</td><td>'.$sGroupLeader.'</td></tr>
				<tr><td class="caption">'.$this->translate('Date Started').'</td><td>'.$sDateStarted.'</td></tr>
				<tr><td class="caption">'.$this->translate('Date Created').'</td><td>'.$sDateCreated.'</td></tr>
				<tr><td class="caption">'.$this->translate('Ministry Theme').'</td><td>'.$aMinistry['ministry_theme'].'</td></tr>
				<tr><td class="caption">'.$this->translate('Members').'</td><td>0</td></tr>
				<tr><td class="caption">'.$this->translate('Description').'</td><td>'.$aMinistry['description'].'</td></tr>
			</tbody>
		</table>
	</div>
	<div class="col-md-6">
		<button type="button" role="button" class="btn btn-primary btn-sm" id="add-edit-ministry-btn">
			<span class="glyphicon glyphicon-edit"></span>
			'.$this->translate('Edit').'
		</button>
		<button type="button" role="button" class="btn btn-'.$sActivateClass.' btn-sm"
			onclick="url(\''.$this->baseUrl().'/chms/activate-ministry/command/'.$sActivate.'/ministry_id/'.$aMinistry['id'].'\')">
			<span class="glyphicon glyphicon-'.$sActivateIcon.'"></span>
			'.$this->translate($sActivate).'
		</button>
		<button type="button" role="button" class="btn btn-danger btn-sm"
		onclick="return confirmDelete(\''.$this->baseUrl().'/chms/delete-ministry/\', '.$aMinistry['id'].')">
			<span class="glyphicon glyphicon-trash"></span>
			'.$this->translate('Delete').'
		</button>
	</div>
</div>';

/* ADD / EDIT DEPARTMENT */
require_once(APPLICATION_PATH . '/jjdev-assets/chms/modals/chms-visitor.phtml');

