<div class="middleBar">
	<h4>3 SM COLUMNS </h4>

	<div class="container" style="border: 1px solid green;">
		<div class="row">
			<div class="col-sm-4">
				One of three columns
			</div>
			<div class="col-sm-4">
				One of three columns
			</div>
			<div class="col-sm-4">
				One of three columns
			</div>
		</div>
	</div>
	<h4>12 COLUMNS </h4>
	<div class="container" style="border: 1px solid blue;">
		<div class="row">
			<div class="col-md-1" style="border-right: 1px solid #000;">.col-md-1</div>
			<div class="col-md-1" style="border-right: 1px solid #000;">.col-md-1</div>
			<div class="col-md-1" style="border-right: 1px solid #000;">.col-md-1</div>
			<div class="col-md-1" style="border-right: 1px solid #000;">.col-md-1</div>
			<div class="col-md-1" style="border-right: 1px solid #000;">.col-md-1</div>
			<div class="col-md-1" style="border-right: 1px solid #000;">.col-md-1</div>
			<div class="col-md-1" style="border-right: 1px solid #000;">.col-md-1</div>
			<div class="col-md-1" style="border-right: 1px solid #000;">.col-md-1</div>
			<div class="col-md-1" style="border-right: 1px solid #000;">.col-md-1</div>
			<div class="col-md-1" style="border-right: 1px solid #000;">.col-md-1</div>
			<div class="col-md-1" style="border-right: 1px solid #000;">.col-md-1</div>
			<div class="col-md-1" style="border-right: 1px solid #000;">.col-md-1</div>
		</div>
	</div>
	<h4> 2 UNEQUAL COLUMNS </h4>

	<div class="row" style="border: 1px solid red;">
		<div class="col-md-8">.col-md-8</div>
		<div class="col-md-4">.col-md-4</div>
	</div>
	<h4>3 MD COLUMNS </h4>

	<div class="row" style="border: 1px solid orange;">
		<div class="col-md-4">.col-md-4</div>
		<div class="col-md-4">.col-md-4</div>
		<div class="col-md-4">.col-md-4</div>
	</div>
	<h4>2 EQUAL COLUMNS </h4>

	<div class="row" style="border: 1px solid black;">
		<div class="col-md-6">.col-md-6</div>
		<div class="col-md-6">.col-md-6</div>
	</div>
</div>