<h2>Progress Bar</h2>
<progress id="james" value="50" max="100"></progress>
<h2>Date Functionality</h2>
Date: <input type="date" name="my-date" id="my-date" class="text ui-widget-content ui-corner-all"/><br/>
DateTime Local: <input type="datetime-local" name="my-date-time-local" id="my-date-time-local" class="text ui-widget-content ui-corner-all"/><br/>
DateTime: <input type="datetime" name="my-date-time" id="my-date-time" class="text ui-widget-content ui-corner-all"/><br/>
Month: <input type="month" name="my-month" id="my-month" class="text ui-widget-content ui-corner-all"/><br/>
Time: <input type="time" name="my-time" id="my-time" class="text ui-widget-content ui-corner-all"/><br/>
Week: <input type="week" name="my-week" id="my-week" class="text ui-widget-content ui-corner-all"/><br/>