<link rel='stylesheet' href='<?php echo $this->baseUrl(); ?>/css/calendar/jquery-ui.min.css' />
<link href='<?php echo $this->baseUrl(); ?>/css/calendar/fullcalendar.css' rel='stylesheet' />
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/calendar/moment.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/calendar/fullcalendar.min.js"></script>


<script>

	$(document).ready(function() {

		$('#calendar').fullCalendar({
			theme: true,
			header: {
				left: 'prev,next today',
				center: 'title',
				right: 'month,agendaWeek,agendaDay'
			},
			defaultDate: '2016-05-12',
			editable: true,
			eventLimit: true, // allow "more" link when too many events
			events: [
				{
					title: 'All Day Event',
					start: '2016-05-01'
				},
				{
					title: 'Long Event',
					start: '2016-05-07',
					end: '2016-05-10'
				},
				{
					id: 999,
					title: 'Repeating Event',
					start: '2016-05-09T16:00:00'
				},
				{
					id: 999,
					title: 'Repeating Event',
					start: '2016-05-16T16:00:00'
				},
				{
					title: 'Conference',
					start: '2016-05-11',
					end: '2016-05-13'
				},
				{
					title: 'Meeting',
					start: '2016-05-12T10:30:00',
					end: '2016-05-12T12:30:00'
				},
				{
					title: 'Lunch',
					start: '2016-05-12T12:00:00'
				},
				{
					title: 'Meeting',
					start: '2016-05-12T14:30:00'
				},
				{
					title: 'Happy Hour',
					start: '2016-05-12T17:30:00'
				},
				{
					title: 'Dinner',
					start: '2016-05-12T20:00:00'
				},
				{
					title: 'Birthday Party',
					start: '2016-05-13T07:00:00'
				},
				{
					title: 'Click for Google',
					url: 'http://google.com/',
					start: '2016-05-28'
				}
			]
		});
		
	});

</script>

	<style rel="stylesheet">

	#calendar {
			max-width: 100%;
			margin: 0 auto;
		}

	</style>
<div class="middleBar" style="width=100%">
	<div id='calendar'></div>
</div>

