<div id="wrapper">
	<!-- Sidebar -->
	<div id="sidebar-wrapper">
		<ul class="sidebar-nav">
			<li class="sidebar-brand">
				<a>Administration</a>
			</li>
			<li>
				<button class="btn btn-default btn-xs btn-block" role="button">
					<div class="pull-left">Dashboard</div>
					<div class="pull-right">&raquo;</div>
				</button>
			</li>
			<li>
				<button class="btn btn-default btn-xs btn-block" role="button">
					<div class="pull-left">Events</div>
					<div class="pull-right">&raquo;</div>
				</button>
			</li>
			<li>
				<button class="btn btn-default btn-xs btn-block" role="button">
					<div class="pull-left">Followups</div>
					<div class="pull-right">&raquo;</div>
				</button>
			</li>
			<li>
				<button class="btn btn-default btn-xs btn-block" role="button">
					<div class="pull-left">Emailing</div>
					<div class="pull-right">&raquo;</div>
				</button>
			</li>
			<li>
				<button class="btn btn-default btn-xs btn-block" role="button">
					<div class="pull-left">Data Export</div>
					<div class="pull-right">&raquo;</div>
				</button>
			</li>
			<li>
				<button class="btn btn-default btn-xs btn-block" role="button">
					<div class="pull-left">Data Import</div>
					<div class="pull-right">&raquo;</div>
				</button>
			</li>
			<li>
				<button class="btn btn-default btn-xs btn-block" role="button">
					<div class="pull-left">General Settings</div>
					<div class="pull-right">&raquo;</div>
				</button>
			</li>
			<li>
				<button class="btn btn-default btn-xs btn-block" role="button">
					<div class="pull-left">Visitors</div>
					<div class="pull-right">&raquo;</div>
				</button>
			</li>
			<li>
				<button class="btn btn-default btn-xs btn-block" role="button">
					<div class="pull-left">Cell Groups</div>
					<div class="pull-right">&raquo;</div>
				</button>
			</li>
			<li>
				<button class="btn btn-default btn-xs btn-block" role="button">
					<div class="pull-left">Ministries</div>
					<div class="pull-right">&raquo;</div>
				</button>
			</li>
			<li>
				<button class="btn btn-default btn-xs btn-block" role="button">
					<div class="pull-left">Projects</div>
					<div class="pull-right">&raquo;</div>
				</button>
			</li>
			<li>
				<button class="btn btn-default btn-xs btn-block" role="button">
					<div class="pull-left">Zones</div>
					<div class="pull-right">&raquo;</div>
				</button>
			</li>
		</ul>
	</div>
	<!-- /#sidebar-wrapper -->

	<!-- Page Content -->
	<div id="page-content-wrapper">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12">
					<a href="#menu-toggle" class="jjdev-text-highlight jjdev-float-left" id="menu-toggle">Toggle Menu</a>
					<h3>A story worthy telling</h3>
					<p>This template has a responsive menu toggling system. The menu will appear collapsed on smaller screens, and will appear non-collapsed on larger screens. When toggled using the button below, the menu will appear/disappear. On small screens, the page content will be pushed off canvas.</p>

					<p>Make sure to keep all page content within the <code>#page-content-wrapper</code>.</p>
				</div>
			</div>
		</div>
	</div>
	<!-- /#page-content-wrapper -->

</div>

<!-- Menu Toggle Script -->
